#!/usr/bin/env node

/**
 * Session Handoff Generator (Phase 15.5)
 *
 * Reads the most recent session summary from Vault/08-Retrospectives/,
 * extracts open items, pending decisions, and in-progress tasks, and writes
 * Vault/00-Inbox/session-handoff-{date}.md for the next session.
 *
 * Called by wrap-up.js at end of day; the handoff is picked up by
 * context-assembly.js (loadSessionHandoff) at next session start.
 *
 * Usage: node .claude/scripts/session-handoff.js
 */

const fs = require('fs');
const path = require('path');

const RETRO_DIR = path.join('Vault', '08-Retrospectives');
const INBOX_DIR = path.join('Vault', '00-Inbox');
const today = new Date().toISOString().split('T')[0];

// Section headings that contain forward-looking / open content
const OPEN_ITEM_SECTIONS = [
  'next steps',
  'next session',
  'open items',
  'pending',
  'pending decisions',
  'in progress',
  'in-progress',
  'follow-up',
  'blockers',
  'known issues'
];

function main() {
  console.log('\n🤝 Session Handoff Generator (Phase 15.5)');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');

  const latest = findLatestSummary();
  if (!latest) {
    console.error('❌ No session summaries found in', RETRO_DIR);
    process.exit(1);
  }

  console.log(`   Source: ${latest.file}`);

  const content = fs.readFileSync(latest.path, 'utf8');
  const sections = extractOpenSections(content);
  const decisions = extractSection(content, ['decisions made', 'decisions']);

  if (sections.length === 0) {
    console.log('   ⚠️  No open-item sections found; writing minimal handoff');
  }

  const handoffPath = path.join(INBOX_DIR, `session-handoff-${today}.md`);
  fs.mkdirSync(INBOX_DIR, { recursive: true });
  fs.writeFileSync(handoffPath, buildHandoff(latest.file, sections, decisions), 'utf8');

  console.log(`   ✅ Handoff written: ${handoffPath}`);
  console.log('✅ HANDOFF COMPLETE\n');
}

/**
 * Find the most recently modified session summary
 */
function findLatestSummary() {
  try {
    const candidates = fs.readdirSync(RETRO_DIR)
      .filter(f => f.startsWith('Session-Summary-') && f.endsWith('.md'))
      .map(f => ({
        file: f,
        path: path.join(RETRO_DIR, f),
        mtime: fs.statSync(path.join(RETRO_DIR, f)).mtimeMs
      }))
      .sort((a, b) => b.mtime - a.mtime);

    return candidates[0] || null;
  } catch (err) {
    return null;
  }
}

/**
 * Extract all sections whose heading matches an open-item keyword
 */
function extractOpenSections(content) {
  const sections = [];

  for (const keyword of OPEN_ITEM_SECTIONS) {
    const body = extractSection(content, [keyword]);
    if (body) {
      sections.push({ heading: keyword, body });
    }
  }

  return sections;
}

/**
 * Extract the body of the first markdown section whose heading contains
 * one of the given keywords (case-insensitive). Body runs until the next
 * heading of same-or-higher level or a horizontal rule.
 */
function extractSection(content, keywords) {
  const lines = content.split('\n');

  for (let i = 0; i < lines.length; i++) {
    const headingMatch = lines[i].match(/^(#{1,4})\s+(.*)$/);
    if (!headingMatch) continue;

    const level = headingMatch[1].length;
    const title = headingMatch[2].toLowerCase();

    if (!keywords.some(k => title.includes(k))) continue;

    const body = [];
    for (let j = i + 1; j < lines.length; j++) {
      const nextHeading = lines[j].match(/^(#{1,4})\s+/);
      if (nextHeading && nextHeading[1].length <= level) break;
      if (/^---\s*$/.test(lines[j])) break;
      body.push(lines[j]);
    }

    const text = body.join('\n').trim();
    if (text) return text;
  }

  return null;
}

/**
 * Build the handoff document
 */
function buildHandoff(sourceFile, sections, decisions) {
  let body = `---
type: log
status: active
authority: sessions
tags: [handoff, session-continuity, phase-15]
source: 08-Retrospectives/${sourceFile}
last_updated: ${today}
---

# Session Handoff — ${today}

**Generated from:** [[../08-Retrospectives/${sourceFile.replace(/\.md$/, '')}]]

`;

  if (sections.length > 0) {
    for (const section of sections) {
      const title = section.heading.replace(/\b\w/g, c => c.toUpperCase());
      body += `## ${title}\n\n${section.body}\n\n`;
    }
  } else {
    body += `## Open Items\n\n_No open items extracted from the last session summary._\n\n`;
  }

  if (decisions) {
    body += `## Decisions From Last Session\n\n${decisions}\n\n`;
  }

  body += `---\n\n_Auto-generated by session-handoff.js. Consumed by context-assembly.js at session start._\n`;

  return body;
}

main();
